

import { JSAData, Language } from './types';

export const TRANSLATIONS = {
  en: {
    appTitle: 'JESA HSE SPA/JSA System',
    subtitle: 'Safe Performance Analysis',
    searchPlaceholder: 'Type job title (e.g., Welding, Excavation)...',
    generateWithAI: 'Generate / Draft',
    hazards: 'Hazards & Risks',
    controls: 'Controls & Measures',
    tools: 'Tools & Equipment',
    steps: 'Job Steps',
    emergency: 'Emergency Contacts',
    riskAssessment: 'Risk Assessment',
    initial: 'Initial Risk',
    residual: 'Residual Risk',
    signatures: 'Validation & Signatures',
    print: 'Download PDF (Official)',
    reset: 'Start Over',
    loading: 'AI is drafting your Safety Analysis...',
    preparedBy: 'Prepared By (Job Performer)',
    approvedBy: 'Approved By (Supervisor)',
    verifiedBy: 'Verified By (HSE)',
    location: 'Location',
    date: 'Date',
    permitNo: 'Permit No',
    likelihood: 'Likelihood',
    severity: 'Severity',
    score: 'Score',
    generateWarning: 'AI Generated - Verify before use',
    meta: {
      company: 'Company / Contractor',
      project: 'Project Name',
      workOrder: 'Work Order #',
      teamLeader: 'Team Leader Name',
      teamMembers: 'Work Team / Participants'
    },
    editor: {
      tabs: {
        general: 'General & Risk',
        details: 'Hazards & Tools',
        steps: 'Work Steps',
        finish: 'Sign & Export'
      },
      addStep: '+ Add Step',
      addHazard: '+ Add Hazard',
      addControl: '+ Add Control',
      addTool: '+ Add Tool',
      riskMatrix: 'Risk Matrix',
      calculate: 'Calculate',
      editMode: 'Edit Mode',
      previewMode: 'Preview Mode',
      jobTitle: 'Job Title',
      category: 'Category',
      requiredPermits: 'Required Permits'
    }
  },
  fr: {
    appTitle: 'Système JESA HSE SPA/JSA',
    subtitle: 'Analyse de la Performance Sécurité',
    searchPlaceholder: 'Tapez le titre (ex. Soudage, Excavation)...',
    generateWithAI: 'Générer / Rédiger',
    hazards: 'Dangers et Risques',
    controls: 'Contrôles et Mesures',
    tools: 'Outils et Équipements',
    steps: 'Étapes du Travail',
    emergency: 'Contacts d\'Urgence',
    riskAssessment: 'Évaluation des Risques',
    initial: 'Risque Initial',
    residual: 'Risque Résiduel',
    signatures: 'Validation et Signatures',
    print: 'Télécharger PDF (Officiel)',
    reset: 'Recommencer',
    loading: 'L\'IA rédige votre analyse de sécurité...',
    preparedBy: 'Préparé Par (Exécutant)',
    approvedBy: 'Approuvé Par (Superviseur)',
    verifiedBy: 'Vérifié Par (HSE)',
    location: 'Lieu',
    date: 'Date',
    permitNo: 'N° Permis',
    likelihood: 'Probabilité',
    severity: 'Sévérité',
    score: 'Score',
    generateWarning: 'Généré par IA - Vérifier avant utilisation',
    meta: {
      company: 'Société / Sous-traitant',
      project: 'Nom du Projet',
      workOrder: 'N° Ordre de Travail',
      teamLeader: 'Chef d\'Équipe',
      teamMembers: 'Équipe de Travail / Participants'
    },
    editor: {
      tabs: {
        general: 'Général & Risques',
        details: 'Dangers & Outils',
        steps: 'Étapes de Travail',
        finish: 'Signer & Exporter'
      },
      addStep: '+ Ajouter Étape',
      addHazard: '+ Ajouter Danger',
      addControl: '+ Ajouter Contrôle',
      addTool: '+ Ajouter Outil',
      riskMatrix: 'Matrice des Risques',
      calculate: 'Calculer',
      editMode: 'Mode Édition',
      previewMode: 'Mode Aperçu',
      jobTitle: 'Titre du Poste',
      category: 'Catégorie',
      requiredPermits: 'Permis Requis'
    }
  },
  ar: {
    appTitle: 'نظام JESA HSE SPA/JSA',
    subtitle: 'تحليل الأداء الآمن',
    searchPlaceholder: 'اكتب اسم الوظيفة (مثلاً: لحام، حفر)...',
    generateWithAI: 'توليد / صياغة',
    hazards: 'المخاطر والتهديدات',
    controls: 'الضوابط والتدابير',
    tools: 'الأدوات والمعدات',
    steps: 'خطوات العمل',
    emergency: 'جهات اتصال الطوارئ',
    riskAssessment: 'تقييم المخاطر',
    initial: 'المخاطر الأولية',
    residual: 'المخاطر المتبقية',
    signatures: 'التحقق والتوقيعات',
    print: 'تحميل الوثيقة PDF (الرسمية)',
    reset: 'البدء من جديد',
    loading: 'الذكاء الاصطناعي يقوم بصياغة تحليل السلامة...',
    preparedBy: 'أعدت بواسطة (المنفذ)',
    approvedBy: 'تمت الموافقة من قبل (المشرف)',
    verifiedBy: 'تم التحقق من قبل (HSE)',
    location: 'الموقع',
    date: 'التاريخ',
    permitNo: 'رقم التصريح',
    likelihood: 'الاحتمالية',
    severity: 'الشدة',
    score: 'النتيجة',
    generateWarning: 'تم إنشاؤه بواسطة الذكاء الاصطناعي - تحقق قبل الاستخدام',
    meta: {
      company: 'الشركة / المقاول',
      project: 'اسم المشروع',
      workOrder: 'رقم أمر العمل',
      teamLeader: 'اسم قائد الفريق',
      teamMembers: 'فريق العمل / المشاركون'
    },
    editor: {
      tabs: {
        general: 'عام والمخاطر',
        details: 'المخاطر والأدوات',
        steps: 'خطوات العمل',
        finish: 'التوقيع والتصدير'
      },
      addStep: '+ إضافة خطوة',
      addHazard: '+ إضافة خطر',
      addControl: '+ إضافة ضابط',
      addTool: '+ إضافة أداة',
      riskMatrix: 'مصفوفة المخاطر',
      calculate: 'حساب',
      editMode: 'وضع التحرير',
      previewMode: 'وضع المعاينة',
      jobTitle: 'عنوان الوظيفة',
      category: 'الفئة',
      requiredPermits: 'التصاريح المطلوبة'
    }
  }
};

export const LOCATIONS = [
  { name: 'Jorf Lasfar JFC 1-5', emergencyPhone: '+212 523 45 67 89', musterPoint: 'Zone A-12' },
  { name: 'Benguérir Mine', emergencyPhone: '+212 524 12 34 56', musterPoint: 'Gate 3' },
  { name: 'Khouribga Site', emergencyPhone: '+212 523 11 22 33', musterPoint: 'Main Office' },
  { name: 'Laayoune Wharf', emergencyPhone: '+212 528 99 88 77', musterPoint: 'Assembly Point 1' },
  { name: 'Maaden P3 (KSA)', emergencyPhone: '+966 13 345 6789', musterPoint: 'Zone 4' },
  { name: 'JESA Casablanca HQ', emergencyPhone: '+212 522 11 22 33', musterPoint: 'Lobby' },
];

export const PROJECTS_LIST = [
  "Jorf Fertilizer Company 1 (JFC1) – DAP Plant",
  "Jorf Fertilizer Company 2 (JFC2) – MAP Plant",
  "Jorf Fertilizer Company 3 (JFC3) – TSP Plant",
  "Jorf Fertilizer Company 4 (JFC4) – Sulfuric Acid Plant",
  "Jorf Fertilizer Company 5 (JFC5) – Phosphoric Acid Plant",
  "Jorf Lasfar Phosphate Hub (JPH)",
  "Jorf Lasfar Port & Wharf Expansion",
  "Khouribga Mine & Washery Upgrade",
  "Benguérir Mine & Processing Plant",
  "Downstream Plant – Phosphate Pulp Drying (Benguérir)",
  "Youssoufia Mine & Facilities",
  "Safi Chemical Complex – TSP Expansion",
  "Boucraa (Phosboucraa) Integrated Fertilizer Platform",
  "Boucraa Conveyor Belt 100 km",
  "Maaden Phosphate 3 – Phase 1 (Wa’ad Al-Shamal & Ras Al-Khair)",
  "Maaden Phosphate 3 – Diammonium Phosphate Plant",
  "Maaden Phosphate 3 – Sulfuric Acid Plants",
  "Maaden Phosphate 3 – Phosphoric Acid Plant",
  "Africa Pipeline Initial Segments",
  "Morocco-Nigeria Pipeline (Feasibility & Initial Studies)",
  "Dire Dawa Fertilizer Plant (Ethiopia)",
  "Abidjan Intercity Bus/Metro Station (Côte d’Ivoire)",
  "Cotonou Electricity Program – 4 Power Projects (Benin)",
  "Dakar 6 Residential Towers & Mall (Senegal)",
  "SNIM Guelb 1 Plant Modernization (Mauritania)",
  "SNIM Nouadhibou Port Expansion (Mauritania)",
  "Eshidiya 2 MTPA Beneficiation Plant (Jordan)",
  "Greater Agadir Agglomeration Infrastructure",
  "Agadir Wastewater Discharge Stations & Transfer Pipe",
  "Casablanca Engineering Center",
  "UM6P Benguérir Campus & Research Labs",
  "OCP America Gainesville Office (Florida)",
  "Integrated Fertilizer Unit – Laayoune",
  "Jorf Lasfar Zero Liquid Discharge (ZLD) System",
  "Jorf Lasfar Desalination Plant Expansion",
  "Khouribga Slurry Pipeline Phase II",
  "Benguérir Green Ammonia Pilot (Pre-FEED completed)",
  "Safi Phosphoric Acid Purification Unit",
  "Jorf Lasfar OSBL Infrastructure",
  "Jorf Lasfar Marine Terminal Upgrade"
];

export const SEED_JOBS: JSAData[] = [
  {
    id: 'job-001',
    title: {
      en: 'Confined Space Welding Operations',
      fr: 'Opérations de soudage en espace confiné',
      ar: 'عمليات اللحام في الأماكن المغلقة'
    },
    metadata: {
      company: 'JESA',
      project: 'Maintenance T2',
      workOrder: 'WO-2025-889',
      teamLeader: 'Ahmed Alami',
      teamMembers: ['Mohammed Karim', 'Youssef Benali', 'Said Tazi']
    },
    category: 'Hot Work',
    locations: LOCATIONS,
    hazards: [
      { id: 'h1', description: 'Oxygen Deficiency', limit: '< 19.5% O2' },
      { id: 'h2', description: 'Toxic Fumes (Welding)', limit: 'Mn > 0.2 mg/m3' },
      { id: 'h3', description: 'Fire / Explosion', limit: 'LEL > 0%' },
      { id: 'h4', description: 'Heat Stress', limit: 'WBGT > 30°C' },
      { id: 'h5', description: 'Electrical Shock', limit: '> 50V AC' },
      { id: 'h6', description: 'Noise', limit: '> 85 dB(A)' },
    ],
    tools: [
      { id: 't1', name: 'Multi-Gas Detector', brandModel: 'Dräger X-am 8000' },
      { id: 't2', name: 'Welding Machine', brandModel: 'Lincoln Electric V270' },
      { id: 't3', name: 'Extraction Fan', brandModel: 'Coppus Vano' },
      { id: 't4', name: 'Tripod & Winch', brandModel: 'MSA Workman' },
      { id: 't5', name: 'Fire Extinguisher', brandModel: '6kg ABC Powder' },
    ],
    controls: [
      { id: 'c1', description: 'Permit to Work (PTW)', type: 'PROCEDURE', standardRef: 'JESA-HSE-PRO-001' },
      { id: 'c2', description: 'Gas Testing every 15 mins', type: 'PROCEDURE', standardRef: 'OSHA 1910.146' },
      { id: 'c3', description: 'Fire Watcher Dedicated', type: 'PROCEDURE', standardRef: 'NFPA 51B' },
      { id: 'c4', description: 'Welding Helmet (Auto-dark)', type: 'PPE', standardRef: 'EN 175' },
      { id: 'c5', description: 'Respirator (P3 Filter)', type: 'PPE', standardRef: 'EN 143' },
      { id: 'c6', description: 'Flame Retardant Coveralls', type: 'PPE', standardRef: 'ISO 11612' },
    ],
    steps: [
      { id: 1, description: 'Verify LOTO and isolate energy sources', hazardRef: 'Electrical Shock' },
      { id: 2, description: 'Perform initial gas test (O2, LEL, H2S, CO)', hazardRef: 'Toxic Fumes' },
      { id: 3, description: 'Install ventilation (blowing/extracting)', hazardRef: 'Oxygen Deficiency' },
      { id: 4, description: 'Setup tripod and rescue harness', hazardRef: 'Entrapment' },
      { id: 5, description: 'Inspect welding equipment and cables', hazardRef: 'Fire / Explosion' },
      { id: 6, description: 'Enter space with attendant at entry', hazardRef: 'Psychological Stress' },
      { id: 7, description: 'Perform welding task (max 30 min shifts)', hazardRef: 'Heat Stress' },
      { id: 8, description: 'Continuous gas monitoring', hazardRef: 'Toxic Fumes' },
    ],
    initialRisk: { likelihood: 4, severity: 5, score: 20, level: 'EXTREME' },
    residualRisk: { likelihood: 2, severity: 4, score: 8, level: 'MEDIUM' },
    requiredPermits: ['Hot Work', 'Confined Space', 'Isolation']
  },
  {
      id: 'job-002',
      title: {
          en: 'Scaffolding Erection & Dismantling',
          fr: 'Montage et Démontage d\'Échafaudage',
          ar: 'تركيب وتفكيك السقالات'
      },
      metadata: { company: '', project: '', workOrder: '', teamLeader: '', teamMembers: [] },
      category: 'Work at Height',
      locations: LOCATIONS,
      hazards: [],
      tools: [],
      controls: [],
      steps: [],
      initialRisk: { likelihood: 0, severity: 0, score: 0, level: 'LOW' },
      residualRisk: { likelihood: 0, severity: 0, score: 0, level: 'LOW' },
      requiredPermits: []
  },
  {
    id: 'job-003',
    title: {
        en: 'Excavation and Trenching > 1.2m',
        fr: 'Excavation et Tranchée > 1.2m',
        ar: 'الحفر والخنادق > 1.2 م'
    },
    metadata: { company: '', project: '', workOrder: '', teamLeader: '', teamMembers: [] },
    category: 'Civil Works',
    locations: LOCATIONS,
    hazards: [],
    tools: [],
    controls: [],
    steps: [],
    initialRisk: { likelihood: 0, severity: 0, score: 0, level: 'LOW' },
    residualRisk: { likelihood: 0, severity: 0, score: 0, level: 'LOW' },
    requiredPermits: []
}
];